// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/cheriehsieh/orchestration/internal/eventstore"
	"github.com/cloudevents/sdk-go/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEventStore creates a new instance of MockEventStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventStore {
	mock := &MockEventStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventStore is an autogenerated mock type for the EventStore type
type MockEventStore struct {
	mock.Mock
}

type MockEventStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventStore) EXPECT() *MockEventStore_Expecter {
	return &MockEventStore_Expecter{mock: &_m.Mock}
}

// Append provides a mock function for the type MockEventStore
func (_mock *MockEventStore) Append(ctx context.Context, event v2.Event) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Append")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v2.Event) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventStore_Append_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Append'
type MockEventStore_Append_Call struct {
	*mock.Call
}

// Append is a helper method to define mock.On call
//   - ctx context.Context
//   - event v2.Event
func (_e *MockEventStore_Expecter) Append(ctx interface{}, event interface{}) *MockEventStore_Append_Call {
	return &MockEventStore_Append_Call{Call: _e.mock.On("Append", ctx, event)}
}

func (_c *MockEventStore_Append_Call) Run(run func(ctx context.Context, event v2.Event)) *MockEventStore_Append_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v2.Event
		if args[1] != nil {
			arg1 = args[1].(v2.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventStore_Append_Call) Return(err error) *MockEventStore_Append_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventStore_Append_Call) RunAndReturn(run func(ctx context.Context, event v2.Event) error) *MockEventStore_Append_Call {
	_c.Call.Return(run)
	return _c
}

// GetBySubject provides a mock function for the type MockEventStore
func (_mock *MockEventStore) GetBySubject(ctx context.Context, subject string) ([]v2.Event, error) {
	ret := _mock.Called(ctx, subject)

	if len(ret) == 0 {
		panic("no return value specified for GetBySubject")
	}

	var r0 []v2.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]v2.Event, error)); ok {
		return returnFunc(ctx, subject)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []v2.Event); ok {
		r0 = returnFunc(ctx, subject)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v2.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, subject)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventStore_GetBySubject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySubject'
type MockEventStore_GetBySubject_Call struct {
	*mock.Call
}

// GetBySubject is a helper method to define mock.On call
//   - ctx context.Context
//   - subject string
func (_e *MockEventStore_Expecter) GetBySubject(ctx interface{}, subject interface{}) *MockEventStore_GetBySubject_Call {
	return &MockEventStore_GetBySubject_Call{Call: _e.mock.On("GetBySubject", ctx, subject)}
}

func (_c *MockEventStore_GetBySubject_Call) Run(run func(ctx context.Context, subject string)) *MockEventStore_GetBySubject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventStore_GetBySubject_Call) Return(vs []v2.Event, err error) *MockEventStore_GetBySubject_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockEventStore_GetBySubject_Call) RunAndReturn(run func(ctx context.Context, subject string) ([]v2.Event, error)) *MockEventStore_GetBySubject_Call {
	_c.Call.Return(run)
	return _c
}

// GetExecutionsByWorkflow provides a mock function for the type MockEventStore
func (_mock *MockEventStore) GetExecutionsByWorkflow(ctx context.Context, workflowID string) ([]eventstore.ExecutionSummary, error) {
	ret := _mock.Called(ctx, workflowID)

	if len(ret) == 0 {
		panic("no return value specified for GetExecutionsByWorkflow")
	}

	var r0 []eventstore.ExecutionSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]eventstore.ExecutionSummary, error)); ok {
		return returnFunc(ctx, workflowID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []eventstore.ExecutionSummary); ok {
		r0 = returnFunc(ctx, workflowID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]eventstore.ExecutionSummary)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, workflowID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventStore_GetExecutionsByWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExecutionsByWorkflow'
type MockEventStore_GetExecutionsByWorkflow_Call struct {
	*mock.Call
}

// GetExecutionsByWorkflow is a helper method to define mock.On call
//   - ctx context.Context
//   - workflowID string
func (_e *MockEventStore_Expecter) GetExecutionsByWorkflow(ctx interface{}, workflowID interface{}) *MockEventStore_GetExecutionsByWorkflow_Call {
	return &MockEventStore_GetExecutionsByWorkflow_Call{Call: _e.mock.On("GetExecutionsByWorkflow", ctx, workflowID)}
}

func (_c *MockEventStore_GetExecutionsByWorkflow_Call) Run(run func(ctx context.Context, workflowID string)) *MockEventStore_GetExecutionsByWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventStore_GetExecutionsByWorkflow_Call) Return(executionSummarys []eventstore.ExecutionSummary, err error) *MockEventStore_GetExecutionsByWorkflow_Call {
	_c.Call.Return(executionSummarys, err)
	return _c
}

func (_c *MockEventStore_GetExecutionsByWorkflow_Call) RunAndReturn(run func(ctx context.Context, workflowID string) ([]eventstore.ExecutionSummary, error)) *MockEventStore_GetExecutionsByWorkflow_Call {
	_c.Call.Return(run)
	return _c
}
