// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/cheriehsieh/orchestration/internal/engine"
	mock "github.com/stretchr/testify/mock"
)

// NewMockJoinStateStore creates a new instance of MockJoinStateStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJoinStateStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJoinStateStore {
	mock := &MockJoinStateStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJoinStateStore is an autogenerated mock type for the JoinStateStore type
type MockJoinStateStore struct {
	mock.Mock
}

type MockJoinStateStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJoinStateStore) EXPECT() *MockJoinStateStore_Expecter {
	return &MockJoinStateStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockJoinStateStore
func (_mock *MockJoinStateStore) Delete(ctx context.Context, executionID string, joinNodeID string) error {
	ret := _mock.Called(ctx, executionID, joinNodeID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, executionID, joinNodeID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJoinStateStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockJoinStateStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - executionID string
//   - joinNodeID string
func (_e *MockJoinStateStore_Expecter) Delete(ctx interface{}, executionID interface{}, joinNodeID interface{}) *MockJoinStateStore_Delete_Call {
	return &MockJoinStateStore_Delete_Call{Call: _e.mock.On("Delete", ctx, executionID, joinNodeID)}
}

func (_c *MockJoinStateStore_Delete_Call) Run(run func(ctx context.Context, executionID string, joinNodeID string)) *MockJoinStateStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJoinStateStore_Delete_Call) Return(err error) *MockJoinStateStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJoinStateStore_Delete_Call) RunAndReturn(run func(ctx context.Context, executionID string, joinNodeID string) error) *MockJoinStateStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockJoinStateStore
func (_mock *MockJoinStateStore) Get(ctx context.Context, executionID string, joinNodeID string) (*engine.PendingJoin, error) {
	ret := _mock.Called(ctx, executionID, joinNodeID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *engine.PendingJoin
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*engine.PendingJoin, error)); ok {
		return returnFunc(ctx, executionID, joinNodeID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *engine.PendingJoin); ok {
		r0 = returnFunc(ctx, executionID, joinNodeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*engine.PendingJoin)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, executionID, joinNodeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJoinStateStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockJoinStateStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - executionID string
//   - joinNodeID string
func (_e *MockJoinStateStore_Expecter) Get(ctx interface{}, executionID interface{}, joinNodeID interface{}) *MockJoinStateStore_Get_Call {
	return &MockJoinStateStore_Get_Call{Call: _e.mock.On("Get", ctx, executionID, joinNodeID)}
}

func (_c *MockJoinStateStore_Get_Call) Run(run func(ctx context.Context, executionID string, joinNodeID string)) *MockJoinStateStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJoinStateStore_Get_Call) Return(pendingJoin *engine.PendingJoin, err error) *MockJoinStateStore_Get_Call {
	_c.Call.Return(pendingJoin, err)
	return _c
}

func (_c *MockJoinStateStore_Get_Call) RunAndReturn(run func(ctx context.Context, executionID string, joinNodeID string) (*engine.PendingJoin, error)) *MockJoinStateStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockJoinStateStore
func (_mock *MockJoinStateStore) Save(ctx context.Context, state *engine.PendingJoin) error {
	ret := _mock.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *engine.PendingJoin) error); ok {
		r0 = returnFunc(ctx, state)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJoinStateStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockJoinStateStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - state *engine.PendingJoin
func (_e *MockJoinStateStore_Expecter) Save(ctx interface{}, state interface{}) *MockJoinStateStore_Save_Call {
	return &MockJoinStateStore_Save_Call{Call: _e.mock.On("Save", ctx, state)}
}

func (_c *MockJoinStateStore_Save_Call) Run(run func(ctx context.Context, state *engine.PendingJoin)) *MockJoinStateStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *engine.PendingJoin
		if args[1] != nil {
			arg1 = args[1].(*engine.PendingJoin)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJoinStateStore_Save_Call) Return(err error) *MockJoinStateStore_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJoinStateStore_Save_Call) RunAndReturn(run func(ctx context.Context, state *engine.PendingJoin) error) *MockJoinStateStore_Save_Call {
	_c.Call.Return(run)
	return _c
}
