// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/cheriehsieh/orchestration/internal/engine"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWorkflowRepository creates a new instance of MockWorkflowRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkflowRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkflowRepository {
	mock := &MockWorkflowRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWorkflowRepository is an autogenerated mock type for the WorkflowRepository type
type MockWorkflowRepository struct {
	mock.Mock
}

type MockWorkflowRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkflowRepository) EXPECT() *MockWorkflowRepository_Expecter {
	return &MockWorkflowRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockWorkflowRepository
func (_mock *MockWorkflowRepository) GetByID(ctx context.Context, workflowID string) (*engine.Workflow, error) {
	ret := _mock.Called(ctx, workflowID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *engine.Workflow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*engine.Workflow, error)); ok {
		return returnFunc(ctx, workflowID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *engine.Workflow); ok {
		r0 = returnFunc(ctx, workflowID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*engine.Workflow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, workflowID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkflowRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockWorkflowRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - workflowID string
func (_e *MockWorkflowRepository_Expecter) GetByID(ctx interface{}, workflowID interface{}) *MockWorkflowRepository_GetByID_Call {
	return &MockWorkflowRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, workflowID)}
}

func (_c *MockWorkflowRepository_GetByID_Call) Run(run func(ctx context.Context, workflowID string)) *MockWorkflowRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkflowRepository_GetByID_Call) Return(workflow *engine.Workflow, err error) *MockWorkflowRepository_GetByID_Call {
	_c.Call.Return(workflow, err)
	return _c
}

func (_c *MockWorkflowRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, workflowID string) (*engine.Workflow, error)) *MockWorkflowRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}
