// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/cheriehsieh/orchestration/internal/eventbus"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSubscriber creates a new instance of MockSubscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubscriber(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubscriber {
	mock := &MockSubscriber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSubscriber is an autogenerated mock type for the Subscriber type
type MockSubscriber struct {
	mock.Mock
}

type MockSubscriber_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubscriber) EXPECT() *MockSubscriber_Expecter {
	return &MockSubscriber_Expecter{mock: &_m.Mock}
}

// Subscribe provides a mock function for the type MockSubscriber
func (_mock *MockSubscriber) Subscribe(ctx context.Context, handler eventbus.EventHandler) error {
	ret := _mock.Called(ctx, handler)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, eventbus.EventHandler) error); ok {
		r0 = returnFunc(ctx, handler)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSubscriber_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockSubscriber_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - handler eventbus.EventHandler
func (_e *MockSubscriber_Expecter) Subscribe(ctx interface{}, handler interface{}) *MockSubscriber_Subscribe_Call {
	return &MockSubscriber_Subscribe_Call{Call: _e.mock.On("Subscribe", ctx, handler)}
}

func (_c *MockSubscriber_Subscribe_Call) Run(run func(ctx context.Context, handler eventbus.EventHandler)) *MockSubscriber_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 eventbus.EventHandler
		if args[1] != nil {
			arg1 = args[1].(eventbus.EventHandler)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubscriber_Subscribe_Call) Return(err error) *MockSubscriber_Subscribe_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSubscriber_Subscribe_Call) RunAndReturn(run func(ctx context.Context, handler eventbus.EventHandler) error) *MockSubscriber_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}
